services:
  sandbox:
    build:
      context: ./docker/sandbox
      dockerfile: Dockerfile-os-${BASE_IMG_NAME}-${BASE_IMG_TAG}-sdk-${BASE_SDK_VERSION}.${COMMON_ENVIRONMENT}
      args:
        - IMG_NAME=${BASE_IMG_NAME}
        - IMG_TAG=${BASE_IMG_TAG}
        - UID=${COMMON_UID}
        - GID=${COMMON_GID}
        - USERNAME=${COMMON_USERNAME:-developer}
        - COMMENT=${COMMON_COMMENT:-Developer}
        - SHELL=${COMMON_SHELL:-sh}
        - TIMEZONE=${COMMON_TIMEZONE:-UTC}
        - SDK_VERSION=${BASE_SDK_VERSION}
    container_name: sandbox
    hostname: sandbox
    restart: no # unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    volumes:
      - "./src/sandbox:/home/${COMMON_USERNAME:-developer}"
      - "sndbx_sandbox_net:/usr/share/dotnet/sdk"
    user: "${COMMON_USERNAME:-developer}"
    working_dir: "/home/${COMMON_USERNAME:-developer}"

  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile.${COMMON_ENVIRONMENT}
      args:
        - IMG_NAME=${POSTGRES_IMG_NAME}
        - IMG_TAG=${POSTGRES_IMG_TAG}
        - TIMEZONE=${COMMON_TIMEZONE:-UTC}
    container_name: sndbx_postgres
    hostname: sndbx_postgres
    restart: no # unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
    volumes:
      - "sndbx_postgres_data:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile.${COMMON_ENVIRONMENT}
      args:
        - IMG_NAME=${MYSQL_IMG_NAME}
        - IMG_TAG=${MYSQL_IMG_TAG}
        - TIMEZONE=${COMMON_TIMEZONE:-UTC}
    container_name: sdbx_mysql
    hostname: sndbx_mysql
    restart: no # unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - "sndbx_mysql_data:/var/lib/mysql"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "$$MYSQL_USER", "-p", "$$MYSQL_PASSWORD"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sndbx_postgres_data:
    name: sndbx_postgres_data
  sndbx_mysql_data:
    name: sndbx_mysql_data
  sndbx_sandbox_net:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/usr/share/dotnet/sdk"
