ARG IMG_NAME=${$IMG_NAME:-debian}
ARG IMG_TAG=${$IMG_TAG:-latest}

FROM ${IMG_NAME}:${IMG_TAG}

ARG IMG_NAME=${IMG_NAME:-debian}
ARG IMG_TAG=${IMG_TAG:-latest}
ARG UID=${UID:-1000}
ARG GID=${GID:-1000}
ARG USERNAME=${USERNAME:-developer}
ARG COMMENT=${COMMENT:-Developer}
ARG SHELL=${SHELL:-bash}
ARG TIMEZONE=${TIMEZONE:-UTC}
ARG SDK_VERSION=${SDK_VERSION:-9.0}

ARG DEBIAN_FRONTEND=noninteractive

ENV TZ="${TIMEZONE}"

RUN apt-get -qq -y update && apt-get -qq -y upgrade \
    && apt-get -qq -y install \
        vim \
        curl \
        wget \
        apt-transport-https \
        sudo \
        git \
        tzdata \
        bash \
        zip unzip \
        libc6 \
        libgcc-s1 \
        libgssapi-krb5-2 \
        libicu72 \
        libssl3 \
        libstdc++6 \
        zlib1g \
        gpg \
    && ln -fs /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata

COPY ${IMG_NAME}-${IMG_TAG}-packages-microsoft-prod.deb /tmp/packages-microsoft-prod.deb

RUN dpkg -i /tmp/packages-microsoft-prod.deb \
    && rm /tmp/packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get -qq -y install dotnet-sdk-${SDK_VERSION}

# Create developer user
RUN addgroup --gid ${GID} ${USERNAME} \
    && adduser --uid ${UID} --gid ${GID} --disabled-password --gecos "${COMMENT}" --shell ${SHELL} ${USERNAME} \
    && usermod -aG sudo ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/casper

USER ${USERNAME}
WORKDIR /home/${USERNAME}
